#!/bin/bash
#
# insta485run
#
# Clean, build and start server
#
# Andrew DeOrio <awdeorio@umich.edu>


# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

# Clean
rm -rf epistolarylanval

# Build
insta485generator epistolarylanvaltemplates -o epistolarylanval

# Serve
cd epistolarylanval
python3 -m http.server 8000